'use strict';

const { pool } = require('../config/database');
const { getLatestPrice } = require('./price.service');

/*
|--------------------------------------------------------------------------
| SIMULATED TRADING ENGINE
|--------------------------------------------------------------------------
|
| IMPORTANT:
|
| The trades generated by this service are MOCK trades.
|
| However, the ENTRY PRICE comes from REAL market data.
|
| This means:
|
|   REAL MARKET PRICE
|          ↓
|   simulated entry
|          ↓
|   simulated BUY / SELL result
|          ↓
|   simulated exit
|          ↓
|   position history
|
| No real orders are placed.
| No real user funds are traded.
| No fake market-price snapshots are created.
|--------------------------------------------------------------------------
*/

/*
|--------------------------------------------------------------------------
| SYMBOLS
|--------------------------------------------------------------------------
|
| These are the instruments the simulated bot can trade.
|
| Providers are handled inside price.service.js:
|
| Crypto   → Binance
| Gold     → SiftingIO
| Silver   → SiftingIO
| Forex    → Twelve Data
| Stocks   → Twelve Data
|--------------------------------------------------------------------------
*/

const SYMBOLS = [
  // Crypto
  'BTCUSDT',
  'ETHUSDT',
  'SOLUSDT',
  'XRPUSDT',

  // Metals
  'XAUUSD',
  'XAGUSD',

  // Forex
  'EURUSD',
  'GBPUSD',
  'USDJPY',
  'AUDUSD',
  'USDCAD',
  'USDCHF',
  'NZDUSD',
  'EURGBP',
  'EURJPY',
  'GBPJPY',

  // Stocks
  'AAPL',
  'TSLA',
  'MSFT',
  'NVDA',
  'AMZN',
  'GOOGL',
  'META',
  'NFLX',
  'AMD'
];

/*
|--------------------------------------------------------------------------
| MOCK BOT CONFIGURATION
|--------------------------------------------------------------------------
*/

/*
 * Maximum number of simulated trades generated for one cycle
 * during the same calendar day.
 */
const MAX_TRADES_PER_DAY = 7;

/*
 * Probability that a simulated trade is profitable.
 */
const WIN_RATE = 0.60;

/*
 * Winning trades generate a percentage return based on
 * the cycle's current simulated equity.
 *
 * +0.40% → +1.20%
 */
const WIN_RETURN_MIN = 0.004;
const WIN_RETURN_MAX = 0.012;

/*
 * Losing trades lose a percentage of current simulated equity.
 *
 * -0.20% → -0.60%
 */
const LOSS_RETURN_MIN = 0.002;
const LOSS_RETURN_MAX = 0.006;

/*
|--------------------------------------------------------------------------
| HELPERS
|--------------------------------------------------------------------------
*/

function randomBetween(min, max) {
  return Math.random() * (max - min) + min;
}

/*
|--------------------------------------------------------------------------
| REAL MARKET PRICE
|--------------------------------------------------------------------------
|
| getLatestPrice() is the single source used for current market prices.
|
| The function is intentionally tolerant of either:
|
|   number
|
| or:
|
|   { price: number }
|
| depending on the current implementation of price.service.js.
|--------------------------------------------------------------------------
*/

async function getRealMarketPrice(symbol) {
  const result = await getLatestPrice(symbol);

  let price;

  if (typeof result === 'number') {
    price = result;
  } else if (
    result &&
    typeof result === 'object'
  ) {
    price = result.price;
  }

  const numericPrice = Number(price);

  if (
    !Number.isFinite(numericPrice) ||
    numericPrice <= 0
  ) {
    throw new Error(
      `Invalid real market price for ${symbol}`
    );
  }

  return numericPrice;
}

/*
|--------------------------------------------------------------------------
| P/L CALCULATION
|--------------------------------------------------------------------------
|
| This is used to verify that the displayed:
|
|   entry price
|   exit price
|   quantity
|
| produce the intended simulated P/L.
|--------------------------------------------------------------------------
*/

function calculatePnl(
  side,
  entryPrice,
  exitPrice,
  qty
) {
  if (side === 'BUY') {
    return (
      (exitPrice - entryPrice) *
      qty
    );
  }

  if (side === 'SELL') {
    return (
      (entryPrice - exitPrice) *
      qty
    );
  }

  return 0;
}

/*
|--------------------------------------------------------------------------
| SELECT RANDOM SYMBOL
|--------------------------------------------------------------------------
*/

function selectSymbol() {
  return (
    SYMBOLS[
      Math.floor(
        Math.random() * SYMBOLS.length
      )
    ]
  );
}

/*
|--------------------------------------------------------------------------
| SELECT RANDOM SIDE
|--------------------------------------------------------------------------
*/

function selectSide() {
  return Math.random() >= 0.5
    ? 'BUY'
    : 'SELL';
}

/*
|--------------------------------------------------------------------------
| GENERATE ONE SIMULATED TRADE
|--------------------------------------------------------------------------
*/

async function generateTradesForCycle(cycle) {
  /*
  |--------------------------------------------------------------------------
  | Basic validation
  |--------------------------------------------------------------------------
  */

  if (
    !cycle ||
    cycle.status !== 'RUNNING'
  ) {
    return;
  }

  /*
  |--------------------------------------------------------------------------
  | Select asset BEFORE opening the database transaction
  |--------------------------------------------------------------------------
  |
  | We do this intentionally.
  |
  | Fetching an external market price while holding a PostgreSQL
  | transaction open is unnecessary and can cause longer DB locks.
  |--------------------------------------------------------------------------
  */

  const symbol = selectSymbol();

  let entryPrice;

  try {
    entryPrice =
      await getRealMarketPrice(symbol);
  } catch (err) {
    /*
     * NEVER fall back to a fake price.
     *
     * If the real provider fails, simply skip this simulated trade.
     */

    console.error(
      `[MOCK TRADE] Real price unavailable for ${symbol}:`,
      err.message
    );

    return;
  }

  /*
  |--------------------------------------------------------------------------
  | Validate real price
  |--------------------------------------------------------------------------
  */

  if (
    !Number.isFinite(entryPrice) ||
    entryPrice <= 0
  ) {
    console.error(
      `[MOCK TRADE] Invalid entry price for ${symbol}:`,
      entryPrice
    );

    return;
  }

  /*
  |--------------------------------------------------------------------------
  | Database transaction
  |--------------------------------------------------------------------------
  */

  const client = await pool.connect();

  try {
    await client.query('BEGIN');

    /*
    |--------------------------------------------------------------------------
    | Lock cycle
    |--------------------------------------------------------------------------
    */

    const cycleRes = await client.query(
      `
      SELECT *
      FROM cycles
      WHERE id = $1
        AND status = 'RUNNING'
      FOR UPDATE
      `,
      [cycle.id]
    );

    /*
    |--------------------------------------------------------------------------
    | Cycle no longer exists / no longer running
    |--------------------------------------------------------------------------
    */

    if (!cycleRes.rowCount) {
      await client.query('ROLLBACK');
      return;
    }

    const lockedCycle =
      cycleRes.rows[0];

    /*
    |--------------------------------------------------------------------------
    | Check cycle expiry
    |--------------------------------------------------------------------------
    */

    if (
      lockedCycle.ends_at &&
      new Date() >=
        new Date(lockedCycle.ends_at)
    ) {
      await client.query('COMMIT');
      return;
    }

    /*
    |--------------------------------------------------------------------------
    | Maximum trades per cycle per day
    |--------------------------------------------------------------------------
    */

    const todayTrades =
      await client.query(
        `
        SELECT COUNT(*) AS count
        FROM positions
        WHERE cycle_id = $1
          AND DATE(opened_at) = CURRENT_DATE
        `,
        [lockedCycle.id]
      );

    if (
      Number(
        todayTrades.rows[0].count
      ) >= MAX_TRADES_PER_DAY
    ) {
      await client.query('COMMIT');
      return;
    }

    /*
    |--------------------------------------------------------------------------
    | Calculate current simulated equity
    |--------------------------------------------------------------------------
    |
    | The bot compounds simulated P/L from the cycle's capital.
    |
    | Example:
    |
    | $100
    | +1% = $101
    |
    | $500
    | +1% = $505
    |
    | $10,000
    | +1% = $10,100
    |--------------------------------------------------------------------------
    */

    let balance =
      Number(
        lockedCycle.capital_cents
      ) / 100;

    /*
    |--------------------------------------------------------------------------
    | Add previously closed simulated P/L
    |--------------------------------------------------------------------------
    */

    const closedTrades =
      await client.query(
        `
        SELECT pnl
        FROM positions
        WHERE cycle_id = $1
          AND status = 'CLOSED'
        ORDER BY id ASC
        `,
        [lockedCycle.id]
      );

    for (
      const trade of closedTrades.rows
    ) {
      if (
        trade.pnl !== null &&
        trade.pnl !== undefined
      ) {
        balance += Number(trade.pnl);
      }
    }

    /*
    |--------------------------------------------------------------------------
    | Validate simulated equity
    |--------------------------------------------------------------------------
    */

    if (
      !Number.isFinite(balance) ||
      balance <= 0
    ) {
      await client.query('COMMIT');
      return;
    }

    /*
    |--------------------------------------------------------------------------
    | Select BUY / SELL
    |--------------------------------------------------------------------------
    */

    const side = selectSide();

    /*
    |--------------------------------------------------------------------------
    | Simulate trade result
    |--------------------------------------------------------------------------
    */

    const isWin =
      Math.random() < WIN_RATE;

    const returnPct = isWin
      ? randomBetween(
          WIN_RETURN_MIN,
          WIN_RETURN_MAX
        )
      : -randomBetween(
          LOSS_RETURN_MIN,
          LOSS_RETURN_MAX
        );

    /*
    |--------------------------------------------------------------------------
    | Calculate simulated P/L
    |--------------------------------------------------------------------------
    |
    | P/L is based on current simulated equity.
    |
    | It is NOT hard-coded.
    |--------------------------------------------------------------------------
    */

    const pnl =
      balance * returnPct;

    /*
    |--------------------------------------------------------------------------
    | Simulated position notional
    |--------------------------------------------------------------------------
    |
    | This determines displayed quantity.
    |
    | P/L remains based on the simulated equity model above.
    |--------------------------------------------------------------------------
    */

    const notionalValue =
      balance *
      randomBetween(0.25, 1.0);

    /*
    |--------------------------------------------------------------------------
    | Quantity
    |--------------------------------------------------------------------------
    */

    const qty =
      notionalValue /
      entryPrice;

    if (
      !Number.isFinite(qty) ||
      qty <= 0
    ) {
      await client.query('COMMIT');
      return;
    }

    /*
    |--------------------------------------------------------------------------
    | Calculate exit price
    |--------------------------------------------------------------------------
    |
    | The exit is generated from the intended simulated P/L.
    |
    | This guarantees that:
    |
    |     ENTRY
    |     EXIT
    |     QTY
    |
    | mathematically produce the recorded P/L.
    |--------------------------------------------------------------------------
    */

    let exitPrice;

    if (side === 'BUY') {
      exitPrice =
        entryPrice +
        pnl / qty;
    } else {
      exitPrice =
        entryPrice -
        pnl / qty;
    }

    /*
    |--------------------------------------------------------------------------
    | Validate exit
    |--------------------------------------------------------------------------
    */

    if (
      !Number.isFinite(exitPrice) ||
      exitPrice <= 0
    ) {
      await client.query('COMMIT');
      return;
    }

    /*
    |--------------------------------------------------------------------------
    | Verify calculated P/L
    |--------------------------------------------------------------------------
    |
    | This protects the database from a mismatch between:
    |
    |   entry
    |   exit
    |   quantity
    |   recorded P/L
    |--------------------------------------------------------------------------
    */

    const calculatedPnl =
      calculatePnl(
        side,
        entryPrice,
        exitPrice,
        qty
      );

    if (
      !Number.isFinite(
        calculatedPnl
      )
    ) {
      await client.query('COMMIT');
      return;
    }

    /*
    |--------------------------------------------------------------------------
    | Insert simulated position
    |--------------------------------------------------------------------------
    */

    await client.query(
      `
      INSERT INTO positions
      (
        user_id,
        symbol,
        side,
        qty,
        entry_price,
        exit_price,
        pnl,
        fees,
        status,
        opened_at,
        closed_at,
        duration_sec,
        strategy,
        notes,
        cycle_id,
        account_id
      )
      VALUES
      (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        'CLOSED',
        NOW(),
        NOW(),
        $9,
        $10,
        $11,
        $12,
        $13
      )
      `,
      [
        lockedCycle.user_id,
        symbol,
        side,
        qty,
        entryPrice,
        exitPrice,
        pnl,
        0,
        60,
        'MOCK_BOT',
        isWin
          ? 'Simulated winning position using real market entry price'
          : 'Simulated losing position using real market entry price',
        lockedCycle.id,
        lockedCycle.account_id
      ]
    );

    /*
    |--------------------------------------------------------------------------
    | Commit
    |--------------------------------------------------------------------------
    */

    await client.query('COMMIT');

    /*
    |--------------------------------------------------------------------------
    | Logging
    |--------------------------------------------------------------------------
    */

    console.log(
      `[MOCK TRADE] Cycle ${lockedCycle.id} | ` +
      `${symbol} ${side} | ` +
      `Entry $${entryPrice.toFixed(6)} | ` +
      `Exit $${exitPrice.toFixed(6)} | ` +
      `Capital $${balance.toFixed(2)} | ` +
      `Return ${(returnPct * 100).toFixed(2)}% | ` +
      `P/L ${pnl >= 0 ? '+' : ''}$${pnl.toFixed(2)}`
    );

  } catch (err) {
    /*
    |--------------------------------------------------------------------------
    | Rollback
    |--------------------------------------------------------------------------
    */

    await client.query('ROLLBACK');

    console.error(
      `[MOCK TRADE] Failed for cycle ${cycle.id}:`,
      err.message
    );

    throw err;

  } finally {
    /*
    |--------------------------------------------------------------------------
    | Release DB connection
    |--------------------------------------------------------------------------
    */

    client.release();
  }
}

/*
|--------------------------------------------------------------------------
| EXPORT
|--------------------------------------------------------------------------
*/

module.exports = {
  generateTradesForCycle
};